### ISSUE TITLE
Handle MySQL Async

### ISSUE THREAD

**Issue by PlayGameDEV** [Seltrox/AutoNick#1]
Hey!

handling the MySQL async is much better to improve the performance. Its so easy how to do if you did not know how, here is a little example. The example is made with Old Methods of MongoDB but it the same way how to use in MySQL. 

https://www.spigotmc.org/wiki/asynchronously-working-with-a-database/

Have fun! 

EDIT: Sry for my bad englisch!  I'm german.

**Comment by Veteranfighter** [comment]
mach doch ne pull request
